field: 70efd76b-1a45-4d21-b91c-b2f42ac298e1 # Colour
fieldLayouts:
  3b6c3db5-4941-4bbb-b41b-d20f1b1d4a44:
    tabs:
      -
        elements:
          -
            fieldUid: da002222-86e5-4f76-a4f4-f6979bcf37dd # Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 438e9233-7f21-4b98-9b91-c70c0682cf82
            warning: null
            width: 100
        name: Content
        uid: 1fe137cc-1f78-4aa4-a9e1-a78aeb49ddd7
fields:
  da002222-86e5-4f76-a4f4-f6979bcf37dd: # Colour
    columnSuffix: gknwblry
    contentColumnType: text
    fieldGroup: null
    handle: colour
    instructions: null
    name: Colour
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: colour
name: Colour
sortOrder: 1
