fieldLayouts:
  68f24513-1bc2-4af2-964c-20011fa89cc6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56c4fa53-7d8b-493f-be19-3816873d0b91
            warning: null
            width: 100
        name: Content
        uid: 906b180c-d450-4b26-ac44-8425f5c7f359
handle: default
hasTitleField: true
name: Default
section: f0b1f77b-fbf2-4b2a-adf6-f33ba62710f3 # Lighting
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
