fieldLayouts:
  fbf56919-125e-4001-9527-98be94d53f23:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98ad9da7-066e-4a6d-8093-6965007c1841
            warning: null
            width: 100
        name: Content
        uid: 95c16dc6-b4dc-44e6-bbdd-f39b91bb041b
handle: downloads
hasTitleField: false
name: Downloads
section: 7eebd11e-6ed4-4dd7-a36d-b317b058f0bd # Downloads
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
