fieldLayouts:
  6fe0f408-aa78-44ec-83b9-79171f630222:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3b2b347f-617a-43c7-899c-fb6bf282aad4
            warning: null
            width: 100
        name: Content
        uid: ffc83f06-5569-4a43-8af2-00549fe9ad61
fs: newsImages
handle: news
name: News
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
