fieldLayouts:
  be712210-398c-45f6-98c2-0fd8920fc234:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 87b22cde-374e-4638-b8e3-ffaed1319bf0
            warning: null
            width: 100
        name: Content
        uid: 782ac919-1c53-4f78-a324-39f92a989e58
fs: profile
handle: profile
name: Profile
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
