columnSuffix: null
contentColumnType: string
fieldGroup: ae90dc43-b53e-45f9-9116-0bb4a8a4177c # Products
handle: colour
instructions: null
name: Colour
searchable: true
settings:
  contentTable: '{{%matrixcontent_colour}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
