columnSuffix: cbuojbvv
contentColumnType: text
fieldGroup: 018ee0ce-e43e-4c51-bed9-77aef78283f0 # News
handle: newsSubtitle
instructions: null
name: 'News Subtitle'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Subtitle goes here'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
