dateModified: 1655389889
email:
  fromEmail: stephen@thinkcreative.uk.com
  fromName: shopcraft.test
  transportType: craft\mail\transportadapters\Sendmail
fs:
  newsImages:
    hasUrls: true
    name: 'News Images'
    settings:
      path: '@webroot/assets/images/news'
    type: craft\fs\Local
    url: '@web/assets/images/news'
  products:
    hasUrls: true
    name: Products
    settings:
      path: '@webroot/assets/images/products'
    type: craft\fs\Local
    url: '@web/assets/images/products'
  profile:
    hasUrls: true
    name: Profile
    settings:
      path: '@webroot/assets/images/profiles'
    type: craft\fs\Local
    url: '@web/assets/images/profiles'
  socials:
    hasUrls: true
    name: Socials
    settings:
      path: '@webroot/assets/images/socials'
    type: craft\fs\Local
    url: '@web/assets/images/socials'
meta:
  __names__:
    1d9cc14c-c78c-4290-ac0d-253e275b6ede: Products # Products
    2b75a1b5-0bf6-40b7-b8f7-a1f2c98dd780: 'Social Icons' # Social Icons
    3ba4ab90-24b0-4020-8c1a-6dbf403f64e7: Warrenty # Warrenty
    3bf2d87c-5779-4157-b511-a029b2cac431: Homepage # Homepage
    3faf2c98-6780-49aa-9d6c-0029edd46adb: 'News Subtitle' # News Subtitle
    004b6149-f84a-45f7-a698-50cc4fef2b53: Colour # Colour
    5eb74ee9-5d9a-4b4b-b9b1-6e085999d2c3: News # News
    6fad7c48-a5e0-428e-a9c5-5165c76a0085: Profile # Profile
    7bcacb04-5b80-41fe-bbe5-2073a96828ab: Wattage # Wattage
    7dbb4434-e376-40cb-8465-e0e5b22c7587: '840x200 Thumb' # 840x200 Thumb
    7eebd11e-6ed4-4dd7-a36d-b317b058f0bd: Downloads # Downloads
    7fa508e4-f0a5-40b3-8edc-1f4707bd4223: 'Shop Craft' # Shop Craft
    7fde589d-f9f0-4b50-b136-2c20dfd405bb: Default # Default
    8b34f526-27aa-4698-a2a3-0c9af7bad0d5: Insulation # Insulation
    9a400b2f-1a31-4045-92dd-c27a71d90e9b: Cart # Cart
    018ee0ce-e43e-4c51-bed9-77aef78283f0: News # News
    35e95d76-112c-4f02-99b6-237f19b96410: Homepage # Homepage
    41af5817-384b-44da-b017-be654cf3e9ca: 'Store Manager' # Store Manager
    54ce4837-0c4f-424c-968a-63e08ea8c9a8: Description # Description
    55bdfbdf-f207-4156-9ef3-fbf183d4a7ff: New # New
    62ebf201-3153-40ee-936a-292818f77a38: Socials # Socials
    70efd76b-1a45-4d21-b91c-b2f42ac298e1: Colour # Colour
    89e3e446-b21f-4add-8030-7e0a70874704: Footer # Footer
    093cebf3-b3f1-4433-a114-0c732a91de91: Contact # Contact
    094d54b8-b941-49ca-b046-db456e1c6ffa: 'News Image' # News Image
    244b4bb5-e0df-40db-a853-a4518395d551: Downloads # Downloads
    521b4746-e762-46dd-aba2-bd3c1985b019: 'Social Image' # Social Image
    534b7489-9626-4f09-93da-5877e9cdbf05: 'News Content' # News Content
    977d4522-6445-4b9f-b396-3a1319545bbd: Footer # Footer
    1056a285-602b-483e-a867-71408912b40b: Default # Default
    07058afe-ea09-490c-ae58-9ba32a8f37a7: 'Number in Pack' # Qty
    9853a717-bf88-4c9b-8f8c-08346a3a329c: Lighting # Lighting
    33824e50-f231-4270-9fa1-ef2dc9a72166: 'Social Link' # Social Link
    93131bf0-7c81-40dd-a31f-70e2a04e6222: SocialIcon # SocialIcon
    a021785b-ae2b-4ca7-b44c-f06fb2d0ed93: News # News
    a07ee649-bca5-48fa-aefe-a2660aa221de: 'News Thumb' # News Thumb
    ae90dc43-b53e-45f9-9116-0bb4a8a4177c: Products # Products
    b1c52873-a358-4151-b2cd-0e88f8f7ef2d: 'Page Content' # Page Content
    b405e1f9-c46b-4acd-a815-9f87af856075: 'Product Image' # Product Image
    c019b179-2ace-490a-87d5-f5ee9e74c2b8: Default # Default
    cbdac6f7-47d4-4d42-83b8-f99ee4bea876: Cart # Cart
    d1ccd105-5325-441d-b2ce-3a7627649a84: Common # Common
    d76a237c-5de4-4682-8783-b77b964483e0: Dummy # Dummy
    d837370e-ef87-40d6-a7a6-12be2660679e: 'Social Icons' # Social Icons
    da002222-86e5-4f76-a4f4-f6979bcf37dd: Colour # Colour
    f0b1f77b-fbf2-4b2a-adf6-f33ba62710f3: Lighting # Lighting
    f0b4e012-f268-4cab-bf6b-a40f26dcad30: Contact # Contact
    f35c9c84-6ac3-489a-b664-cc4fffb6dd22: shopcraft.test # shopcraft.test
    f35095cc-d353-486c-b0db-6b4e54964845: Insulation # Insulation
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: 6SPM85GGJBBXT7M9TRIUGQI9
    schemaVersion: 4.0.1
    settings:
      activeCartDuration: 3600
      allowCheckoutWithoutPayment: false
      allowEmptyCartOnCheckout: false
      allowPartialPaymentOnCheckout: false
      autoSetCartShippingMethodOption: false
      autoSetNewCartAddresses: true
      cartVariable: cart
      defaultView: commerce/orders
      dimensionUnits: mm
      emailSenderAddress: null
      emailSenderAddressPlaceholder: null
      emailSenderName: 'Shopping with Craft'
      emailSenderNamePlaceholder: null
      freeOrderPaymentStrategy: complete
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      minimumTotalPriceStrategy: zero
      orderReferenceFormat: '{{number[:7]}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      showEditUserCommerceTab: true
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      validateCartCustomFieldsOnSubmission: false
      weightUnits: kg
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 5VLAJT11I0OXPZUA8D99WPM3
    schemaVersion: 3.0.11
  store-hours:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
system:
  edition: pro
  live: true
  name: shopcraft.test
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: UTC
