dateModified: 1655221827
email:
  fromEmail: stephen@thinkcreative.uk.com
  fromName: shopcraft.test
  transportType: craft\mail\transportadapters\Sendmail
fs:
  newsImages:
    hasUrls: true
    name: 'News Images'
    settings:
      path: '@webroot/assets/images/news'
    type: craft\fs\Local
    url: '@web/assets/images/news'
meta:
  __names__:
    3bf2d87c-5779-4157-b511-a029b2cac431: Homepage # Homepage
    3faf2c98-6780-49aa-9d6c-0029edd46adb: 'News Subtitle' # News Subtitle
    5eb74ee9-5d9a-4b4b-b9b1-6e085999d2c3: News # News
    7dbb4434-e376-40cb-8465-e0e5b22c7587: '840x200 Thumb' # 840x200 Thumb
    7eebd11e-6ed4-4dd7-a36d-b317b058f0bd: Downloads # Downloads
    7fa508e4-f0a5-40b3-8edc-1f4707bd4223: 'Shop Craft' # Shop Craft
    7fde589d-f9f0-4b50-b136-2c20dfd405bb: Default # Default
    018ee0ce-e43e-4c51-bed9-77aef78283f0: News # News
    35e95d76-112c-4f02-99b6-237f19b96410: Homepage # Homepage
    55bdfbdf-f207-4156-9ef3-fbf183d4a7ff: New # New
    093cebf3-b3f1-4433-a114-0c732a91de91: Contact # Contact
    094d54b8-b941-49ca-b046-db456e1c6ffa: 'News Image' # News Image
    244b4bb5-e0df-40db-a853-a4518395d551: Downloads # Downloads
    534b7489-9626-4f09-93da-5877e9cdbf05: 'News Content' # News Content
    9853a717-bf88-4c9b-8f8c-08346a3a329c: Lighting # Lighting
    a021785b-ae2b-4ca7-b44c-f06fb2d0ed93: News # News
    ae90dc43-b53e-45f9-9116-0bb4a8a4177c: Products # Products
    b1c52873-a358-4151-b2cd-0e88f8f7ef2d: 'Page Content' # Page Content
    c019b179-2ace-490a-87d5-f5ee9e74c2b8: Default # Default
    d1ccd105-5325-441d-b2ce-3a7627649a84: Common # Common
    d76a237c-5de4-4682-8783-b77b964483e0: Dummy # Dummy
    f0b1f77b-fbf2-4b2a-adf6-f33ba62710f3: Lighting # Lighting
    f0b4e012-f268-4cab-bf6b-a40f26dcad30: Contact # Contact
    f35c9c84-6ac3-489a-b664-cc4fffb6dd22: shopcraft.test # shopcraft.test
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: 6SPM85GGJBBXT7M9TRIUGQI9
    schemaVersion: 4.0.1
    settings:
      activeCartDuration: 3600
      allowCheckoutWithoutPayment: false
      allowEmptyCartOnCheckout: false
      allowPartialPaymentOnCheckout: false
      autoSetCartShippingMethodOption: false
      autoSetNewCartAddresses: true
      cartVariable: cart
      defaultView: commerce/orders
      dimensionUnits: cm
      emailSenderAddress: null
      emailSenderAddressPlaceholder: null
      emailSenderName: null
      emailSenderNamePlaceholder: null
      freeOrderPaymentStrategy: complete
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      minimumTotalPriceStrategy: zero
      orderReferenceFormat: '{{number[:7]}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      showEditUserCommerceTab: true
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      validateCartCustomFieldsOnSubmission: false
      weightUnits: kg
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.11
  store-hours:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
system:
  edition: pro
  live: true
  name: shopcraft.test
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: UTC
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
