defaultPlacement: end
enableVersioning: true
handle: insulation
name: Insulation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7fa508e4-f0a5-40b3-8edc-1f4707bd4223: # Shop Craft
    enabledByDefault: true
    hasUrls: true
    template: insulation/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 62582420-5fb7-4896-9bcd-faaba6068cce
type: structure
